metricbeat:
  modules:
    - module: apache
      metricsets: ["status"]
      hosts: ["http://127.0.0.1/server-status"]
      period: 10s
      enabled: true
    - module: system
      metricsets:
      # CPU stats
      - cpu

      # System Load stats
      - load

      # Per CPU core stats
      - core

      # IO stats
      - diskio

      # Per filesystem stats
      - filesystem

      # File system summary stats
      - fsstat

      # Memory stats
      - memory

      # Network stats
      - network

      # Per process stats
      - process
      enabled: true
      period: 10s
      processes: ['.*']
    - module: postgresql
      metricsets:
        # Stats about every PostgreSQL database
        - database

        # Stats about the background writer process's activity
        - bgwriter

        # Stats about every PostgreSQL process
        - activity

      enabled: true
      period: 10s

      # The host must be passed as PostgreSQL DSN. Example:
      # postgres://pqgotest:password@localhost:5432?sslmode=disable
      # The available parameters are documented here:
      # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
      hosts: ["postgres://docker:docker@127.0.0.1:5432?dbname=transmart"]
output.elasticsearch:
  hosts: ['http://127.0.0.1:9200/']
      
