version: '2'

services:
  tmweb:
    build: ./transmart-web
    depends_on:
      - tmapp
      - tmelk
    network_mode: host
    restart: always
  tmapp:
    build: ./transmart-app
    ports:
      - "127.0.0.1:8009:8009"
    depends_on:
      - tmdb
      - tmsolr
    restart: always
  tmdb:
    build: ./transmart-db
    ports:
      - "127.0.0.1:5432:5432"
    depends_on:
      - tmelk
    restart: always
  tmsolr:
    build: ./transmart-solr
    restart: always
  tmrserve:
    build: ./transmart-rserve
    volumes_from:
      - tmapp
    restart: always
  tmload:
    build: ./transmart-load
    depends_on:
      - tmdb
  tmelk:
    build: ./transmart-elk
    ports:
      - "127.0.0.1:5601:5601"
      - "127.0.0.1:5044:5044"
      - "127.0.0.1:9200:9200"
    restart: always
